version: "2"
services:
  fts:
    image: rucio/fts
    container_name: fts
    hostname: fts
    ports:
      - "8446:8446"
      - "8449:8449"
    links:
      - db:db
    depends_on:
      - db
  db:
    image: mysql:5
    container_name: ftsdb
    hostname: ftsdb
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
    ports:
      - "3306:3306"
